# Generated by Django 4.2.5 on 2023-11-22 21:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_id', models.CharField(default=app.models.generate_short_id, max_length=6, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
