# Generated by Django 4.2.5 on 2023-12-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_shortenedurl_count_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
