# Generated by Django 4.2.5 on 2023-12-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shortenedurl_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
